services:
  qbittor:
    image: davift/qbittor:latest
    # Uncomment the following lines to build localy.
    # image: alpine:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    volumes:
      - ./qBittorrent:/var/lib/qbittorrent/.config/qBittorrent/
      - /tmp:/TORRENT
    ports:
      - "8080:8080"
